### PR TITLE
TAO-948 Printed tests: maths not present

### PR DESCRIPTION
**Pull request by hutnikau**

### CODE REVIEW

**Comment by krampstudio** [comment]
I've got an error that prevents me to generate the test. 

```
An error occurred while rendering a page : Error in template rendering : TypeError: renderer is null
```

With the given stack trace : 

```
TypeError: renderer is null
Stack trace:
Renderer/this.renderTpl@http://taopba.localdomain/taoQtiItem/views/js/qtiRunner/core/Renderer.js:269:29
Element<.render@http://taopba.localdomain/taoQtiItem/views/js/qtiItem/core/Element.js:300:29
QtiInteraction<.render@http://taopba.localdomain/taoQtiItem/views/js/qtiItem/core/interactions/Interaction.js:110:20
Class.extend/prototype[name]</<@http://taopba.localdomain/tao/views/js/lib/class.js:36:31
BlockInteraction<.render@http://taopba.localdomain/taoQtiItem/views/js/qtiItem/core/interactions/BlockInteraction.js:33:20
Class.extend/prototype[name]</<@http://taopba.localdomain/tao/views/js/lib/class.js:36:31
Container<.render@http://taopba.localdomain/taoQtiItem/views/js/qtiItem/core/Container.js:112:48
Class.extend/prototype[name]</<@http://taopba.localdomain/tao/views/js/lib/class.js:36:31
Element<.render@http://taopba.localdomain/taoQtiItem/views/js/qtiItem/core/Element.js:289:36
render@http://taopba.localdomain/taoQtiPrint/views/js/runner/provider/qtiprint.js:66:37
itemRunnerFactory/ItemRunner.render@http://taopba.localdomain/taoItems/views/js/runner/api/itemRunner.js:301:25
itemRunnerFactory/ItemRunner.render/<@http://taopba.localdomain/taoItems/views/js/runner/api/itemRunner.js:280:25
initDone/<@http://taopba.localdomain/taoItems/views/js/runner/api/itemRunner.js:172:33
Dt@http://taopba.localdomain/tao/views/js/lib/lodash.min.js:24:35
initDone@http://taopba.localdomain/taoItems/views/js/runner/api/itemRunner.js:170:25
init/</<@http://taopba.localdomain/taoQtiPrint/views/js/runner/provider/qtiprint.js:53:25
Renderer/this.load/<@http://taopba.localdomain/taoQtiItem/views/js/qtiRunner/core/Renderer.js:564:21
newContext/context.execCb@http://taopba.localdomain/tao/views/js/lib/require.js:1658:24
newContext/Module.prototype.check@http://taopba.localdomain/tao/views/js/lib/require.js:874:43
newContext/Module.prototype.enable/</<@http://taopba.localdomain/tao/views/js/lib/require.js:1121:29
bind/<@http://taopba.localdomain/tao/views/js/lib/require.js:132:20
newContext/Module.prototype.emit/<@http://taopba.localdomain/tao/views/js/lib/require.js:1164:21
each@http://taopba.localdomain/tao/views/js/lib/require.js:57:31
newContext/Module.prototype.emit@http://taopba.localdomain/tao/views/js/lib/require.js:1163:17
newContext/Module.prototype.check@http://taopba.localdomain/tao/views/js/lib/require.js:925:25
newContext/Module.prototype.enable/</<@http://taopba.localdomain/tao/views/js/lib/require.js:1121:29
bind/<@http://taopba.localdomain/tao/views/js/lib/require.js:132:20
newContext/Module.prototype.emit/<@http://taopba.localdomain/tao/views/js/lib/require.js:1164:21
each@http://taopba.localdomain/tao/views/js/lib/require.js:57:31
newContext/Module.prototype.emit@http://taopba.localdomain/tao/views/js/lib/require.js:1163:17
newContext/Module.prototype.check@http://taopba.localdomain/tao/views/js/lib/require.js:925:25
newContext/Module.prototype.enable@http://taopba.localdomain/tao/views/js/lib/require.js:1151:17
newContext/Module.prototype.init@http://taopba.localdomain/tao/views/js/lib/require.js:782:21
newContext/Module.prototype.callPlugin/</<@http://taopba.localdomain/tao/views/js/lib/require.js:967:1
bind/<@http://taopba.localdomain/tao/views/js/lib/require.js:132:20
newContext/Module.prototype.emit/<@http://taopba.localdomain/tao/views/js/lib/require.js:1164:21
each@http://taopba.localdomain/tao/views/js/lib/require.js:57:31
newContext/Module.prototype.emit@http://taopba.localdomain/tao/views/js/lib/require.js:1163:17
newContext/Module.prototype.check@http://taopba.localdomain/tao/views/js/lib/require.js:925:25
newContext/Module.prototype.enable@http://taopba.localdomain/tao/views/js/lib/require.js:1151:17
newContext/Module.prototype.init@http://taopba.localdomain/tao/views/js/lib/require.js:782:21
newContext/Module.prototype.callPlugin/</load<@http://taopba.localdomain/tao/views/js/lib/require.js:999:1
bind/<@http://taopba.localdomain/tao/views/js/lib/require.js:132:20
.load/<@http://taopba.localdomain/tao/views/js/tpl.js:104:21
newContext/context.execCb@http://taopba.localdomain/tao/views/js/lib/require.js:1658:24
newContext/Module.prototype.check@http://taopba.localdomain/tao/views/js/lib/require.js:874:43
newContext/Module.prototype.enable/</<@http://taopba.localdomain/tao/views/js/lib/require.js:1121:29
bind/<@http://taopba.localdomain/tao/views/js/lib/require.js:132:20
newContext/Module.prototype.emit/<@http://taopba.localdomain/tao/views/js/lib/require.js:1164:21
each@http://taopba.localdomain/tao/views/js/lib/require.js:57:31
newContext/Module.prototype.emit@http://taopba.localdomain/tao/views/js/lib/require.js:1163:17
newContext/Module.prototype.check@http://taopba.localdomain/tao/views/js/lib/require.js:925:25
newContext/Module.prototype.enable@http://taopba.localdomain/tao/views/js/lib/require.js:1151:17
newContext/Module.prototype.init@http://taopba.localdomain/tao/views/js/lib/require.js:782:21
newContext/Module.prototype.callPlugin/</load<@http://taopba.localdomain/tao/views/js/lib/require.js:999:1
bind/<@http://taopba.localdomain/tao/views/js/lib/require.js:132:20
text.finishLoad@http://taopba.localdomain/tao/views/js/lib/text/text.js:152:13
text.load/<@http://taopba.localdomain/tao/views/js/lib/text/text.js:188:21
text.get/xhr.onreadystatechange@http://taopba.localdomain/tao/views/js/lib/text/text.js:295:25
 qtiprint.js:68:21
```

**Comment by hutnikau** [comment]
Please review this PR:
https://github.com/oat-sa/extension-tao-itemqti/pull/338
and test the current again.

**Comment by krampstudio** [comment]
I'm still  unable to get maths rendered in the pdf. The pdf was generated after the 1st run (without maths) and stale when I regenerated.

**Comment by krampstudio** [comment]
Reassigning to you @llecaque for the follow up

**Comment by krampstudio** [comment]
Also https://github.com/oat-sa/extension-tao-itemqti/pull/366 may fix it...

**Comment by antoinerobin** [comment]
https://github.com/oat-sa/extension-tao-booklet/pull/11 fix it
You also have to have a full mathjax in itemqti, at least a mathjax install with fonts/HTML-CSS/TeX/png/*

**Comment by ssipasseuth** [comment]
If `fonts/HTML-CSS/TeX/png/*` is required, I would suggest updating our install script http://forge.taotesting.com/projects/tao/wiki/Enable_math to reflect this requirement otherwise our user may get into the same issue.

**Comment by antoinerobin** [comment]
this task is already in the jira, I will probably make it on Monday .

**Comment by ssipasseuth** [comment]
Ok, cool thanks. I gonna wait for the new script so I can test all together.

**Comment by ssipasseuth** [comment]
requires https://github.com/oat-sa/extension-tao-booklet/pull/11

**Pull request merged**
